# Generated by Django 4.1.2 on 2022-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='payment_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата за месяц'),
        ),
    ]
