# Generated by Django 4.1.2 on 2022-10-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_email_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='customer',
        ),
    ]
