# Generated by Django 4.1.2 on 2022-10-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_box_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='rental_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания аренды'),
        ),
        migrations.AlterField(
            model_name='box',
            name='rental_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала аренды'),
        ),
    ]
