# Generated by Django 4.1.2 on 2022-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_box_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.IntegerField(null=True, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='box',
            name='square',
            field=models.IntegerField(null=True, verbose_name='Площадь'),
        ),
    ]
