# Generated by Django 4.1.2 on 2022-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_box_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='total_boxes',
            field=models.IntegerField(null=True),
        ),
    ]
