# Generated by Django 4.1.2 on 2022-10-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_storage_total_boxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='is_use',
            new_name='in_use',
        ),
    ]
