# Generated by Django 4.1.2 on 2022-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_is_use_box_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='payment_per_month',
            field=models.IntegerField(verbose_name='Оплата за месяц'),
        ),
    ]
