# Generated by Django 4.1.2 on 2022-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_storage_payment_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='photo',
        ),
        migrations.AddField(
            model_name='storage',
            name='large_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Большое фото'),
        ),
        migrations.AddField(
            model_name='storage',
            name='small_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Маленькое фото'),
        ),
    ]
