# Generated by Django 4.1.2 on 2022-10-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_storage_photo_storage_large_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='store.customer', verbose_name='Клиент'),
        ),
    ]
