# Generated by Django 4.1.2 on 2022-10-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.IntegerField(null=True, verbose_name='Объём'),
        ),
    ]
