# Generated by Django 4.1.2 on 2022-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_box_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
