# Generated by Django 4.1.2 on 2022-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_box_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='large_photo',
            field=models.ImageField(blank=True, default='image2.png', upload_to='', verbose_name='Большое фото'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='small_photo',
            field=models.ImageField(blank=True, default='image9.png', upload_to='', verbose_name='Маленькое фото'),
        ),
    ]
